#

configfile: "config.json"

RAW_COUNT_FILES = [
    '{}/GSM2758471_PJ016.filtered.matrix.txt'.format(config['raw_data_dir']),
    '{}/GSM2758472_PJ017.filtered.matrix.txt'.format(config['raw_data_dir']),
    '{}/GSM2758473_PJ018.filtered.matrix.txt'.format(config['raw_data_dir']),
    '{}/GSM2758474_PJ025.filtered.matrix.txt'.format(config['raw_data_dir']),
    '{}/GSM2758475_PJ030.filtered.matrix.txt'.format(config['raw_data_dir']),
    '{}/GSM2758476_PJ032.filtered.matrix.txt'.format(config['raw_data_dir']),
    '{}/GSM2758477_PJ035.filtered.matrix.txt'.format(config['raw_data_dir']),
    '{}/GSM2940098_PJ048.filtered.matrix.txt'.format(config['raw_data_dir'])
]

ZIPPED_RAW_COUNT_FILES = [
    '{}/GSM2758471_PJ016.filtered.matrix.txt.gz'.format(config['raw_data_dir']),
    '{}/GSM2758472_PJ017.filtered.matrix.txt.gz'.format(config['raw_data_dir']),
    '{}/GSM2758473_PJ018.filtered.matrix.txt.gz'.format(config['raw_data_dir']),
    '{}/GSM2758474_PJ025.filtered.matrix.txt.gz'.format(config['raw_data_dir']),
    '{}/GSM2758475_PJ030.filtered.matrix.txt.gz'.format(config['raw_data_dir']),
    '{}/GSM2758476_PJ032.filtered.matrix.txt.gz'.format(config['raw_data_dir']),
    '{}/GSM2758477_PJ035.filtered.matrix.txt.gz'.format(config['raw_data_dir']),
    '{}/GSM2940098_PJ048.filtered.matrix.txt.gz'.format(config['raw_data_dir'])
]


rule all:
    input:
        '{}/GSE103224.h5'.format(config['data_dir']),
        '{}/GSE103224_normalized.h5'.format(config['data_dir'])

rule download_data:
    output:
        '{}/GSE103224_RAW.tar'.format(config['raw_data_dir'])
    run:
        commands=[
            'mkdir -p {}'.format(config['raw_data_dir']),
            'curl ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE103nnn/GSE103224/suppl/GSE103224_RAW.tar > {output}'
        ]
        for c in commands:
            shell(c)    

rule unzip_data:
    input:
        '{}/GSE103224_RAW.tar'.format(config['raw_data_dir'])
    output:
        RAW_COUNT_FILES
    run:
        commands = [
            'tar -xf {raw}/GSE103224_RAW.tar -C {raw}'.format(
                raw=config['raw_data_dir']
            )
        ]
        commands += [
            'gunzip {}'.format(f)
            for f in ZIPPED_RAW_COUNT_FILES
        ]
        for c in commands:
            shell(c)

rule build_GSE103224_H5:
    input:
        RAW_COUNT_FILES
    output:
        '{}/GSE103224.h5'.format(config['data_dir'])
    run:
        commands = [
            'mkdir -p {}'.format(config['data_dir']),
            'python build_h5_GSE103224.py {raw} {{output}}'.format(
                raw=config['raw_data_dir']
            )
        ]
        for c in commands:
            shell(c)

rule build_GSE103224_normalized_H5:
    input:
        '{}/GSE103224.h5'.format(config['data_dir'])
    output:
        '{}/GSE103224_normalized.h5'.format(config['data_dir'])
    run:
        shell(
            'python build_h5_GSE103224_normalized.py {input} {output}'
        )
