#

TUMORS = [
    'PJ016',
    'PJ018',
    'PJ048',
    'PJ030',
    'PJ025',
    'PJ035',
    'PJ017',
    'PJ032'
]

configfile: "config.json"

rule all:
    input:
        '{out}/{biomarker}/common_GO_terms_heatmap.png'.format(
            out=config['out_dir'],
            biomarker=config['biomarker']
        ),
        expand(
            '{out}/{{tumor}}_PHATE_clusters.png'.format(
                out=config['out_dir']
            ),
            tumor=TUMORS
        )

rule cluster_tumors:
    output:
        '{}/cluster_de_genes.json'.format(config['tmp_dir']),
        expand(
            '{tmp}/{{tumor}}_clusters.tsv'.format(
                tmp=config['tmp_dir']
            ),
            tumor=TUMORS
        )
    run:
        shell(
            'python cluster_and_de.py -r {} -o {}'.format(
                config['louvain_resolution'],
                config['tmp_dir']
            )
        )


rule identify_clusters_expressing_biomarker:
    input:
        clusts=expand(
            '{tmp}/{{tumor}}_clusters.tsv'.format(
                tmp=config['tmp_dir']
            ),
            tumor=TUMORS
        ),
        de_genes='{}/cluster_de_genes.json'.format(config['tmp_dir'])
    output:
        '{tmp}/{biomarker}/cluster_fraction_biomarker.json'.format(
            tmp=config['tmp_dir'],
            biomarker=config['biomarker']
        ),
        '{tmp}/{biomarker}/clusters_expressing_biomarker.tsv'.format(
            tmp=config['tmp_dir'],
            biomarker=config['biomarker']
        )
    run:
        shell(
            'mkdir -p {tmp}/{biomarker}'.format(
                biomarker=config['biomarker'],
                tmp=config['tmp_dir']
            )
        )
        shell(
            'python identify_clusters_expressing_biomarker.py {biomarker} {tmp} {{input.de_genes}} -o {tmp}/{biomarker}'.format(
                biomarker=config['biomarker'],
                tmp=config['tmp_dir']
            )
        )


rule gsea_per_cluster:
    input:
        '{}/cluster_de_genes.json'.format(config['tmp_dir'])
    output:
        '{}/gsea_results.tsv'.format(config['tmp_dir'])        
    run:
        shell(
            'python gsea.py {{input}} -o {out}'.format(
                out=config['tmp_dir']
            )
        )


rule analyze_cluster_gsea:
    input:
        clusts='{tmp}/{biomarker}/clusters_expressing_biomarker.tsv'.format(
            tmp=config['tmp_dir'],
            biomarker=config['biomarker']
        ),
        gsea='{}/gsea_results.tsv'.format(config['tmp_dir'])
    output:
        '{out}/{biomarker}/common_GO_terms_heatmap.png'.format(
            out=config['out_dir'],
            biomarker=config['biomarker']
        )
    run:
        shell(
            'mkdir -p {out}/{biomarker}'.format(
                out=config['out_dir'],
                biomarker=config['biomarker']
            )
        ),
        shell(
            'python analyze_cluster_gsea.py {{input.gsea}} {{input.clusts}} -o {out}/{biomarker}'.format(
                out=config['out_dir'],
                biomarker=config['biomarker']
            )
        )

rule assign_cell_types:
    output:
        expand(
            '{out}/{{tumor}}_predicted_cell_types.tsv'.format(
                out=config['tmp_dir']
            ),
            tumor=TUMORS
        ),
        expand(
            '{out}/{{tumor}}_predicted_cell_type_probs.tsv'.format(
                out=config['tmp_dir']
            ),
            tumor=TUMORS
        )
    run:
        shell(
            'Rscript assign_cell_types.R {data} {tmp} {data}/cell_type_markers.json'.format(
                tmp=config['tmp_dir'],
                data=config['data_dir']
            )
        )

rule run_phate_per_tumor:
    output:
        expand(
            '{out}/{{tumor}}_PHATE.tsv'.format(
                out=config['tmp_dir']
            ),
            tumor=TUMORS
        )
    run:
        shell(
            'python run_phate_per_tumor.py -o {}'.format(
                config['tmp_dir']
            )            
        )

rule plot_clusters:
    input:
        expand(
            '{tmp}/{{tumor}}_clusters.tsv'.format(
                tmp=config['tmp_dir']
            ),
            tumor=TUMORS
        ),
        expand(
            '{out}/{{tumor}}_PHATE.tsv'.format(
                out=config['tmp_dir']
            ),
            tumor=TUMORS
        )
    output:
        expand(
            '{out}/{{tumor}}_PHATE_clusters.png'.format(
                out=config['out_dir']
            ),
            tumor=TUMORS
        )
    run:
        shell(
            'python phate_color_by_cluster.py {tmp} -o {out}'.format(
                tmp=config['tmp_dir'],
                out=config['out_dir']
            )
        )

rule plot_biomarker:
    output:
        expand(
            '{out}/{biomarker}/{{tumor}}_PHATE_{biomarker}.png'.format(
                out=config['out_dir'],
                biomarker=config['biomarker']
            ),
            tumor=TUMORS
        )
    run:
        shell(
            'mkdir -p {out}/{biomarker}'.format(
                out=config['out_dir'],
                biomarker=config['biomarker']
            )
        ),
        shell(
            'python phate_color_by_gene.py {biomarker} -o {out}/{biomarker}'.format(
                biomarker=config['biomarker'],
                out=config['out_dir']
            )
        )

# Common DE genes across clusters



